#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t wave"

$L " _  _   __   _  _  ____  __   ____ "
$L "/ )( \ / _\ / )( \(  __)/  \ / ___)"
$L "\ /\ //    \\ \/ / ) _)(  O )\___ \"
$L "(_/\_)\_/\_/ \__/ (____)\__/ (____/"
$L "Welcome to Android `getprop ro.build.version.release` / by WaveOS";
